import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/shared/navbar";
import Footer from "@/components/shared/footer";

const playfairDisplay = localFont({
  src: [
    {
      path: './fonts/playfair-display/PlayfairDisplay-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/playfair-display/PlayfairDisplay-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-playfair-display', // Optional custom CSS variable
});

export const metadata: Metadata = {
  title: "Campora",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfairDisplay.variable} antialiased overflow-auto scrollbar-hide`}
      >
        <main className="relative w-full">
          <Navbar />
          <main className="w-full">
            {children}
          </main>
          <Footer />
        </main>
      </body>
    </html>
  );
}
